
let PRIMARY = '#89B53A';
// export let SECONDARY = '#767676';
let WHITE = '#FFFFFF';
let BLACK = '#000000';
let TEXT_COLOR = '#4D5153';
let LIGHT_BORDER_COLOR = '#D5D5D5';

// ACTIONS
let SUCCESS = '#2ecc71';
let WARNING = '#e67e22';
let ALERT = '#e74c3c';

// GRAYSCALE
let GRAY_LIGHT = '#E6E9EC';
let GRAY_MEDIUM = '#E1E2E2';
let GRAY_DARK = '#D3D3D3';



export {
    PRIMARY,
    WHITE,
    BLACK,
    TEXT_COLOR,
    LIGHT_BORDER_COLOR,
    SUCCESS,
    WARNING,
    ALERT,
    GRAY_LIGHT,
    GRAY_MEDIUM,
    GRAY_DARK,
}