export const INCOMPLETE_INVENTORY = 'INCOMPLETE_INVENTORY';
export const PENDING_COORDINATE_IMAGE_UPLOAD = 'PENDING_IMAGE_UPLOAD';
export const PENDING_DATA_UPLOAD = 'PENDING_DATA_UPLOAD';
export const PENDING_IMAGES_UPLOAD = 'PENDING_IMAGES_UPLOAD';
export const INVENTORY_UPLOAD_COMPLETED = 'INVENTORY_UPLOAD_COMPLETED';
