export const INCOMPLETE = 'INCOMPLETE';
export const INCOMPLETE_SAMPLE_TREE = 'INCOMPLETE_SAMPLE_TREE';
export const PENDING_DATA_UPLOAD = 'PENDING_DATA_UPLOAD';
export const PENDING_IMAGE_UPLOAD = 'PENDING_IMAGE_UPLOAD';
export const SYNCED = 'SYNCED';
