export enum RealmSchema {
  Coordinates = 'Coordinates',
  Polygon = 'Polygon',
  Species = 'Species',
  OfflineMap = 'OfflineMap',
  AdditionalDetail = 'AdditionalDetail',
  SampleTree = 'SampleTree',
  Inventory = 'Inventory',
  Intervention = 'Intervention',
  User = 'User',
  ActivityLog = 'ActivityLog',
  ScientificSpecies = 'ScientificSpecies',
  ProjectSite = 'ProjectSite',
  Projects = 'Projects',
  DropdownOption = 'DropdownOption',
  Dropdown = 'Dropdown',
  Input = 'Input',
  YesNo = 'YesNo',
  Element = 'Element',
  Form = 'Form',
  Metadata = 'Metadata'
}
