import {RegisterFormSliceInitalState} from 'src/types/interface/slice.interface'

export const MultiTreeFormData: RegisterFormSliceInitalState = {
  form_id: '',
  key: 'multi-tree-registeration',
  title: 'Multi Tree Registeration',
  intervention_date: 0,
  skip_intervention_form: false,
  project_id: '',
  site_id: '',
  location_type: 'Polygon',
  location_title: 'Select Location',
  coordinates: [],
  preview_blank_polygon: true,
  cover_image_url: '',
  species_required: true,
  is_multi_species: true,
  species_count_required: true,
  species_modal_message: 'did you plant?',
  species_modal_unit: 'Tree Count',
  species: [],
  has_sample_trees: true,
  tree_details_required: true,
  tree_details: [],
  form_details: [],
  user_type: '',
  project_name: '',
  site_name: '',
  meta_data: '',
  form_data: [],
  intervention_type: 'single-tree-registration',
  can_be_entire_site: true,
  entire_site_selected: false,
  additional_data: ''
}
