require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'treemapper' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'treemapperTests' do
    inherit! :complete
    # Pods for testing
  end

  pre_install do |installer|
    # Mapbox
    $RNMBGL.pre_install(installer)
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!('Flipper' => '0.81.0')
  post_install do |installer|
    # Mapbox
    $RNMBGL.post_install(installer)
    flipper_post_install(installer)
  end
end
