require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'treemapper' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Mapbox
  # pod 'react-native-mapbox-gl/DynamicLibrary', :path => '../node_modules/@react-native-mapbox-gl/maps'



  target 'treemapperTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!('Flipper' => '0.62.0')
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'treemapper-tvOS' do
  # Pods for treemapper-tvOS

  target 'treemapper-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
