'use client';

import { useEffect, useRef, useState } from 'react';
import Map, { Source, Layer, Marker, NavigationControl, GeolocateControl } from 'react-map-gl/maplibre';
import { AlertTriangle, Crosshair, Maximize2 } from 'lucide-react';
import 'maplibre-gl/dist/maplibre-gl.css';
import * as turf from '@turf/turf';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { Coord } from '../utils/plotGeometry';

const STREET_STYLE = 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json';

const SATELLITE_STYLE = {
  version: 8 as const,
  sources: {
    'esri-satellite': {
      type: 'raster' as const,
      tiles: ['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],
      tileSize: 256,
      attribution: '© Esri',
    },
  },
  layers: [{ id: 'esri-satellite-layer', type: 'raster' as const, source: 'esri-satellite' }],
};

const fillLayer: any = {
  id: 'boundary-fill',
  type: 'fill',
  paint: { 'fill-color': '#007A49', 'fill-opacity': 0.22 },
};

const outlineLayer: any = {
  id: 'boundary-outline',
  type: 'line',
  paint: { 'line-color': '#007A49', 'line-width': 2.5 },
};

const focusOutlineLayer: any = {
  id: 'focus-outline',
  type: 'line',
  paint: { 'line-color': '#64748b', 'line-width': 1.5, 'line-dasharray': [2, 2] },
};

/** Same two colours the mobile app uses for planted trees and recruits. */
export const ORIGIN_COLOR: Record<string, string> = {
  planted: '#007A49',
  recruit: '#2F80ED',
};

export interface MapPoint {
  id: string;
  latitude: number;
  longitude: number;
  origin?: string;
  label?: string | null;
  outside?: boolean;
}

/**
 * The plot boundary map. Clicking sets the plot centre; the boundary polygon
 * itself is generated by the caller from that centre plus the exact dimensions
 * the user types, so the shape stays a true circle or rectangle of the stated
 * size. Tree points can be overlaid, which the review step uses read-only.
 */
const PlotBoundaryMap = ({
  boundary,
  center,
  onPickCenter,
  focusGeometry,
  points = [],
  height = 420,
  readOnly = false,
}: {
  boundary: GeoJSON.Polygon | null;
  center: Coord | null;
  onPickCenter?: (center: Coord) => void;
  /** Site or project geometry to open on before a boundary exists. */
  focusGeometry?: any | null;
  points?: MapPoint[];
  height?: number;
  readOnly?: boolean;
}) => {
  const mapRef = useRef<any>(null);
  const [isSatellite, setIsSatellite] = useState(true);
  const [mapError, setMapError] = useState<string | null>(null);
  // Auto-fit follows meaningful changes only. Typing a radius should redraw the
  // shape without yanking the viewport on every keystroke.
  const fittedKey = useRef<string>('');

  const fitTo = (geometry: any) => {
    if (!mapRef.current || !geometry) return;
    try {
      const [minLng, minLat, maxLng, maxLat] = turf.bbox(geometry);
      mapRef.current.fitBounds(
        [[minLng, minLat], [maxLng, maxLat]],
        { padding: 60, duration: 800, maxZoom: 19 },
      );
    } catch {
      // bbox throws on degenerate geometry; leave the current view alone.
    }
  };

  const fitToPlot = () => {
    if (boundary) fitTo(boundary);
    else if (center) {
      mapRef.current?.flyTo({ center, zoom: 18, duration: 800 });
    }
  };

  useEffect(() => {
    const key = center ? `c:${center[0].toFixed(6)},${center[1].toFixed(6)}` : 'none';
    if (key === fittedKey.current) return;
    fittedKey.current = key;
    if (boundary) fitTo(boundary);
    else if (center) mapRef.current?.flyTo({ center, zoom: 18, duration: 800 });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [center]);

  useEffect(() => {
    // Open on the chosen site until the user has placed a centre.
    if (center || !focusGeometry) return;
    fitTo(focusGeometry);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [focusGeometry]);

  if (mapError) {
    return (
      <div
        className="flex flex-col items-center justify-center bg-muted border border-dashed rounded-lg text-center px-4"
        style={{ height }}
      >
        <AlertTriangle className="w-8 h-8 text-muted-foreground mb-2" />
        <p className="text-sm text-muted-foreground">Map unavailable</p>
        <p className="text-xs text-muted-foreground/70 mt-1">
          You can still type the centre coordinates by hand.
        </p>
      </div>
    );
  }

  return (
    <div className="relative w-full overflow-hidden rounded-lg border" style={{ height }}>
      <Map
        ref={mapRef}
        style={{ width: '100%', height: '100%' }}
        mapStyle={isSatellite ? (SATELLITE_STYLE as any) : STREET_STYLE}
        attributionControl={false}
        reuseMaps
        cursor={readOnly ? 'grab' : 'crosshair'}
        onClick={(e: any) => {
          if (readOnly || !onPickCenter) return;
          onPickCenter([e.lngLat.lng, e.lngLat.lat]);
        }}
        onError={(e: any) => setMapError(e?.error?.message || 'Failed to load map')}
        initialViewState={{ longitude: 10, latitude: 20, zoom: 1.6 }}
      >
        <NavigationControl position="bottom-right" showCompass={false} />
        {!readOnly && <GeolocateControl position="bottom-right" trackUserLocation={false} />}

        {focusGeometry && !boundary && (
          <Source id="focus-source" type="geojson" data={focusGeometry}>
            <Layer {...focusOutlineLayer} />
          </Source>
        )}

        {boundary && (
          <Source
            id="boundary-source"
            type="geojson"
            data={boundary}
            key={`${boundary.coordinates[0]?.length}-${boundary.coordinates[0]?.[0]?.join(',')}`}
          >
            <Layer {...fillLayer} />
            <Layer {...outlineLayer} />
          </Source>
        )}

        {center && (
          <Marker longitude={center[0]} latitude={center[1]} draggable={!readOnly}
            onDragEnd={(e: any) => onPickCenter?.([e.lngLat.lng, e.lngLat.lat])}
          >
            <span
              title="Plot centre"
              className={cn(
                'block w-3.5 h-3.5 rounded-full border-2 border-white shadow-md bg-[#007A49]',
                !readOnly && 'cursor-move',
              )}
            />
          </Marker>
        )}

        {points.map((p) => (
          <Marker key={p.id} longitude={p.longitude} latitude={p.latitude}>
            <span
              title={p.label || p.origin || 'tree'}
              className={cn(
                'block w-2.5 h-2.5 rounded-full border shadow',
                p.outside ? 'border-amber-500 border-2' : 'border-white',
              )}
              style={{ backgroundColor: ORIGIN_COLOR[(p.origin || 'planted').toLowerCase()] || ORIGIN_COLOR.planted }}
            />
          </Marker>
        ))}
      </Map>

      {!readOnly && !center && (
        <div className="absolute top-2 left-1/2 -translate-x-1/2 bg-background/95 border rounded px-3 py-1.5 shadow-sm">
          <p className="text-[12px] font-medium inline-flex items-center gap-1.5">
            <Crosshair className="w-3.5 h-3.5 text-[#007A49]" />
            Click the map to place the plot centre
          </p>
        </div>
      )}

      <div className="absolute top-2 right-2 flex gap-1.5">
        {(boundary || center) && (
          <Button
            type="button"
            variant="secondary"
            size="sm"
            className="h-7 px-2 text-[11px] shadow"
            onClick={fitToPlot}
          >
            <Maximize2 className="w-3 h-3 mr-1" /> Fit
          </Button>
        )}
        <Button
          type="button"
          variant="secondary"
          size="sm"
          className="h-7 px-2 text-[11px] shadow"
          onClick={() => setIsSatellite((v) => !v)}
        >
          {isSatellite ? 'Map' : 'Satellite'}
        </Button>
      </div>

      <div className="absolute bottom-1.5 left-2 text-[10px] text-white/90 drop-shadow">
        {isSatellite ? '© Esri' : '© CartoDB'}
      </div>
    </div>
  );
};

export default PlotBoundaryMap;
