const { withAndroidManifest } = require('expo/config-plugins')

/**
 * Keeps the app in portrait when the camera opens on a tablet.
 *
 * A large screen ignores an app's requested orientation -- on a Pixel Tablet
 * `adb shell wm get-ignore-orientation-request` reports true for display 0 --
 * so `android:screenOrientation="portrait"` is not honoured there. On top of
 * that, Android's `DisplayRotationCompatPolicy` force-rotates a
 * portrait-locked app to landscape the moment it opens the camera, so that a
 * preview written for portrait still matches the sensor. `dumpsys window`
 * shows it switching to `SCREEN_ORIENTATION_LANDSCAPE` with
 * `isTreatmentEnabledForActivity=true` exactly when the app appears in
 * `mPackageToCameraIdMap`.
 *
 * That treatment is the reason the take-picture screen, and only that screen,
 * flipped to landscape. react-native-vision-camera already tracks sensor
 * orientation itself (`HybridDeviceOrientationManager`), so the compatibility
 * rotation buys us nothing and we opt out of it.
 *
 * This lives in a plugin rather than in `android/app/src/main/AndroidManifest.xml`
 * because `android/` is gitignored and regenerated by `expo prebuild`; an edit
 * made directly in the manifest is lost on the next prebuild.
 */
const PROPERTY = 'android.window.PROPERTY_CAMERA_COMPAT_ALLOW_FORCE_ROTATION'

const withCameraCompatOptOut = (config) =>
  withAndroidManifest(config, (cfg) => {
    const application = cfg.modResults?.manifest?.application?.[0]
    if (!application) {
      throw new Error(
        'withCameraCompatOptOut: no <application> in the Android manifest',
      )
    }

    application.property = application.property ?? []
    const existing = application.property.find(
      (entry) => entry?.$?.['android:name'] === PROPERTY,
    )
    if (existing) {
      existing.$['android:value'] = 'false'
    } else {
      application.property.push({
        $: { 'android:name': PROPERTY, 'android:value': 'false' },
      })
    }

    return cfg
  })

module.exports = withCameraCompatOptOut
